#!/usr/bin/env bash
# Generate .env file from environment variables at build time

cat > .env << EOF
APP_NAME="${APP_NAME:-Won Nyaci Run 2026}"
APP_ENV=${APP_ENV:-production}
APP_KEY=${APP_KEY:-}
APP_DEBUG=${APP_DEBUG:-false}
APP_URL=${APP_URL:-}
VITE_API_URL=${VITE_API_URL:-}

LOG_CHANNEL=stack
LOG_LEVEL=${LOG_LEVEL:-debug}

DB_CONNECTION=mysql
DB_HOST=${MYSQLHOST:-${DB_HOST:-127.0.0.1}}
DB_PORT=${MYSQLPORT:-${DB_PORT:-3306}}
DB_DATABASE=${MYSQLDATABASE:-${DB_DATABASE:-won_nyaci_run}}
DB_USERNAME=${MYSQLUSER:-${DB_USERNAME:-root}}
DB_PASSWORD=${MYSQLPASSWORD:-${DB_PASSWORD:-}}

SESSION_DRIVER=database
SESSION_LIFETIME=${SESSION_LIFETIME:-120}
SESSION_ENCRYPT=${SESSION_ENCRYPT:-false}
SESSION_PATH=${SESSION_PATH:-/}
SESSION_DOMAIN=${SESSION_DOMAIN:-null}

FILESYSTEM_DISK=${FILESYSTEM_DISK:-public}
QUEUE_CONNECTION=database
CACHE_STORE=database

MAIL_MAILER=${MAIL_MAILER:-log}
MAIL_HOST=${MAIL_HOST:-127.0.0.1}
MAIL_PORT=${MAIL_PORT:-2525}
MAIL_USERNAME=${MAIL_USERNAME:-null}
MAIL_PASSWORD=${MAIL_PASSWORD:-null}
MAIL_ENCRYPTION=${MAIL_ENCRYPTION:-null}
MAIL_FROM_ADDRESS=${MAIL_FROM_ADDRESS:-"hello@wonnyacirun.ug"}
MAIL_FROM_NAME=${MAIL_FROM_NAME:-"Won Nyaci Run 2026"}

X_USERNAME=${X_USERNAME:-}
X_BEARER_TOKEN=${X_BEARER_TOKEN:-}
X_CACHE_MINUTES=${X_CACHE_MINUTES:-5}

ADMIN_EMAIL=${ADMIN_EMAIL:-admin@wonnyacirun.ug}
ADMIN_PASSWORD=${ADMIN_PASSWORD:-ChangeMe!2026}
EOF

chmod 600 .env
echo ".env file created successfully"
