-- Won Nyaci Run 2026 MySQL starter database
-- Generated from the supplied run/payment references. Verify banking/payment details with the organisers before live use.
CREATE DATABASE IF NOT EXISTS won_nyaci_run CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
USE won_nyaci_run;
CREATE TABLE users (id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,name VARCHAR(255) NOT NULL,email VARCHAR(255) NOT NULL UNIQUE,password VARCHAR(255) NOT NULL,is_admin TINYINT(1) NOT NULL DEFAULT 0,remember_token VARCHAR(100) NULL,created_at TIMESTAMP NULL,updated_at TIMESTAMP NULL) ENGINE=InnoDB;
CREATE TABLE posts (id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,title VARCHAR(190) NOT NULL,slug VARCHAR(190) NOT NULL UNIQUE,excerpt TEXT NULL,body LONGTEXT NOT NULL,image VARCHAR(255) NULL,published_at TIMESTAMP NULL,is_published TINYINT(1) NOT NULL DEFAULT 0,created_at TIMESTAMP NULL,updated_at TIMESTAMP NULL) ENGINE=InnoDB;
CREATE TABLE contact_messages (id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,name VARCHAR(120) NOT NULL,email VARCHAR(190) NOT NULL,phone VARCHAR(50) NULL,subject VARCHAR(190) NULL,message TEXT NOT NULL,is_read TINYINT(1) NOT NULL DEFAULT 0,created_at TIMESTAMP NULL,updated_at TIMESTAMP NULL) ENGINE=InnoDB;
CREATE TABLE payment_settings (id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,method VARCHAR(255) NOT NULL,label VARCHAR(190) NOT NULL,details JSON NOT NULL,sort_order INT UNSIGNED NOT NULL DEFAULT 0,is_active TINYINT(1) NOT NULL DEFAULT 1,created_at TIMESTAMP NULL,updated_at TIMESTAMP NULL) ENGINE=InnoDB;
CREATE TABLE site_settings (id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,`key` VARCHAR(255) NOT NULL UNIQUE,value TEXT NULL,created_at TIMESTAMP NULL,updated_at TIMESTAMP NULL) ENGINE=InnoDB;
CREATE TABLE x_posts (id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,tweet_id VARCHAR(255) NOT NULL UNIQUE,text TEXT NOT NULL,url TEXT NOT NULL,author_username VARCHAR(255) NULL,media JSON NULL,published_at TIMESTAMP NULL,created_at TIMESTAMP NULL,updated_at TIMESTAMP NULL) ENGINE=InnoDB;
CREATE TABLE cache (`key` VARCHAR(255) PRIMARY KEY,value MEDIUMTEXT NOT NULL,expiration INT NOT NULL) ENGINE=InnoDB;
CREATE TABLE sessions (id VARCHAR(255) PRIMARY KEY,user_id BIGINT UNSIGNED NULL,ip_address VARCHAR(45) NULL,user_agent TEXT NULL,payload TEXT NOT NULL,last_activity INT NOT NULL,INDEX(last_activity),INDEX(user_id)) ENGINE=InnoDB;
INSERT INTO users VALUES (1,'Won Nyaci Run Admin','admin@wonnyacirun.ug','$2y$12$KNMZGwAohW6ZRl5lKuWY5O6NtoAvzHlX7Ud4eibYOyMyBZTwUR9Ie',1,NULL,NOW(),NOW());
INSERT INTO site_settings (`key`,value,created_at,updated_at) VALUES ('tagline','Running for our culture, our health & our future.',NOW(),NOW()),('whatsapp','256775384975',NOW(),NOW()),('x_username','',NOW(),NOW());
INSERT INTO payment_settings (method,label,details,sort_order,is_active,created_at,updated_at) VALUES
('mtn','MTN MOBILE MONEY',JSON_OBJECT('dial_code','*165*4*4#','merchant_code','WCCM','reference','Sponsor’s Full Name','amount','Enter your kit amount','note','Use the official merchant flow shown in the supplied payment reference.'),1,1,NOW(),NOW()),
('airtel','AIRTEL MONEY',JSON_OBJECT('instruction','Use the official Won Nyaci Run/Airtel Money merchant instructions.','reference','Sponsor’s Full Name','amount','UGX 30,000 standard kit'),2,1,NOW(),NOW()),
('stanbic','STANBIC FLEXI-PAY',JSON_OBJECT('instruction','Use the official Stanbic Flexi-Pay option for the run.','reference','Sponsor’s Full Name'),3,1,NOW(),NOW()),
('bank','BANK TRANSFER',JSON_OBJECT('bank','CENTENARY','account_name','WON NYACI ME LANGO','account_number','310010849','note','Verify account details against the latest official run notice before publishing/accepting payment.'),4,1,NOW(),NOW());
INSERT INTO posts (title,slug,excerpt,body,image,published_at,is_published,created_at,updated_at) VALUES ('Welcome to Won Nyaci Run 2026','welcome-to-won-nyaci-run-2026','Running for our culture, our health and our future.','On 24 October 2026, Lango comes together at Old Akii Bua Stadium for a day of movement, culture and practical community impact. Every kit contributes to a collective effort supporting free wheelchairs and crutches for people living with disabilities in Lango. Registration and aerobics begin at 6:00 AM, with running at 7:30 AM.','images/run-flyer-social.png','2026-09-14 07:00:00',1,NOW(),NOW());
