<template><AdminLayout title="Clans"><div v-if="message" class="admin-notice">{{ message }}</div><div v-if="error" class="admin-error">{{ error }}</div><div class="admin-card"><h2>{{ editing ? 'Edit clan' : 'Add a clan' }}</h2><form @submit.prevent="save"><div class="field"><label>Clan name *</label><input v-model="form.name" required></div><div class="field"><label>Clan head / Awitong</label><input v-model="form.awitong"></div><div class="field"><label>Where the majority are found</label><input v-model="form.majority_location"></div><div class="field"><label>Details</label><textarea v-model="form.description" rows="5"></textarea></div><div class="field"><label>Photo</label><input type="file" accept="image/*" @change="event => form.image = event.target.files[0]"></div><label><input type="checkbox" v-model="form.is_published"> Publish publicly</label><br><button class="btn btn-primary" :disabled="saving">{{ saving ? 'Saving…' : (editing ? 'Update clan' : 'Publish clan') }}</button><button v-if="editing" type="button" class="btn btn-secondary" @click="reset">Cancel</button></form></div><div class="admin-card"><h2>Clan profiles</h2><table class="table"><thead><tr><th>Name</th><th>Awitong</th><th>Location</th><th>Status</th><th></th></tr></thead><tbody><tr v-for="clan in clans" :key="clan.id"><td>{{ clan.name }}</td><td>{{ clan.awitong }}</td><td>{{ clan.majority_location }}</td><td>{{ clan.is_published ? 'Published' : 'Draft' }}</td><td><button class="copy-btn" @click="edit(clan)">Edit</button> <button class="copy-btn danger-btn" @click="remove(clan)">Delete</button></td></tr></tbody></table></div></AdminLayout></template>
<script setup>
import { ref, reactive, onMounted } from 'vue'
import axios from 'axios'
import AdminLayout from '../components/AdminLayout.vue'
const clans = ref([]), editing = ref(null), saving = ref(false), message = ref(''), error = ref('')
const form = reactive({ name: '', awitong: '', majority_location: '', description: '', image: null, is_published: false })
const load = async () => { try { clans.value = (await axios.get('/api/admin/clans')).data } catch (e) { error.value = e.response?.data?.message || 'Could not load clans.' } }
const reset = () => { editing.value = null; Object.assign(form, { name: '', awitong: '', majority_location: '', description: '', image: null, is_published: false }) }
const edit = (clan) => { editing.value = clan; Object.assign(form, { ...clan, image: null }) }
const save = async () => { saving.value = true; error.value = ''; const data = new FormData(); Object.entries(form).forEach(([key, value]) => { if (value !== null && value !== undefined) data.append(key, key === 'is_published' ? (value ? '1' : '0') : value) }); try { if (editing.value) { data.append('_method', 'PUT'); await axios.post(`/api/admin/clans/${editing.value.id}`, data); message.value = 'Clan updated.' } else { await axios.post('/api/admin/clans', data); message.value = 'Clan published.' } reset(); await load() } catch (e) { error.value = e.response?.data?.message || 'Could not save clan.' } finally { saving.value = false } }
const remove = async (clan) => { if (!confirm(`Delete ${clan.name}?`)) return; await axios.delete(`/api/admin/clans/${clan.id}`); message.value = 'Clan deleted.'; await load() }
onMounted(load)
</script>
