<template><AdminLayout title="Practice Hub"><div v-if="message" class="admin-notice">{{ message }}</div><div v-if="error" class="admin-error">{{ error }}</div><div class="admin-card"><h2>{{ editing ? 'Edit resource' : 'Add practice resource' }}</h2><form @submit.prevent="save"><div class="field"><label>Title *</label><input v-model="form.title" placeholder="Morning aerobic warm-up" required></div><div class="field"><label>Type</label><select v-model="form.type"><option value="video">Video</option><option value="audio">Audio</option><option value="link">External link</option></select></div><div class="field"><label>Video or audio URL *</label><input v-model="form.media_url" type="url" placeholder="https://youtube.com/..." required></div><div class="field"><label>Instructions</label><textarea v-model="form.description" rows="4"></textarea></div><label><input type="checkbox" v-model="form.is_published"> Publish publicly</label><br><button class="btn btn-primary" :disabled="saving">{{ saving ? 'Saving…' : (editing ? 'Update resource' : 'Publish resource') }}</button><button v-if="editing" type="button" class="btn btn-secondary" @click="reset">Cancel</button></form></div><div class="admin-card"><h2>Published and draft resources</h2><table class="table"><thead><tr><th>Title</th><th>Type</th><th>URL</th><th>Status</th><th></th></tr></thead><tbody><tr v-for="resource in resources" :key="resource.id"><td>{{ resource.title }}</td><td>{{ resource.type }}</td><td class="url-cell">{{ resource.media_url }}</td><td>{{ resource.is_published ? 'Published' : 'Draft' }}</td><td><button class="copy-btn" @click="edit(resource)">Edit</button> <button class="copy-btn danger-btn" @click="remove(resource)">Delete</button></td></tr></tbody></table></div></AdminLayout></template>
<script setup>
import { ref, reactive, onMounted } from 'vue'
import axios from 'axios'
import AdminLayout from '../components/AdminLayout.vue'
const resources = ref([]), editing = ref(null), saving = ref(false), message = ref(''), error = ref('')
const form = reactive({ title: '', type: 'video', media_url: '', description: '', is_published: false })
const load = async () => { try { resources.value = (await axios.get('/api/admin/practice')).data } catch (e) { error.value = e.response?.data?.message || 'Could not load practice resources.' } }
const reset = () => { editing.value = null; Object.assign(form, { title: '', type: 'video', media_url: '', description: '', is_published: false }) }
const edit = (resource) => { editing.value = resource; Object.assign(form, resource) }
const save = async () => { saving.value = true; error.value = ''; try { if (editing.value) { await axios.put(`/api/admin/practice/${editing.value.id}`, form); message.value = 'Practice resource updated.' } else { await axios.post('/api/admin/practice', form); message.value = 'Practice resource published.' } reset(); await load() } catch (e) { error.value = e.response?.data?.message || 'Could not save practice resource.' } finally { saving.value = false } }
const remove = async (resource) => { if (!confirm(`Delete ${resource.title}?`)) return; await axios.delete(`/api/admin/practice/${resource.id}`); message.value = 'Practice resource deleted.'; await load() }
onMounted(load)
</script>
