<template><AdminLayout title="Partners"><div v-if="message" class="admin-notice">{{ message }}</div><div v-if="error" class="admin-error">{{ error }}</div><div class="admin-card"><h2>{{ editing ? 'Edit partner' : 'Recognise a partner' }}</h2><form @submit.prevent="save"><div class="field"><label>Partner name *</label><input v-model="form.name" required></div><div class="field"><label>Category</label><input v-model="form.category" placeholder="Community, corporate, media..."></div><div class="field"><label>Recognition details</label><textarea v-model="form.description" rows="4"></textarea></div><div class="field"><label>Website</label><input v-model="form.website_url" type="url"></div><div class="field"><label>Logo</label><input type="file" accept="image/*" @change="event => form.logo = event.target.files[0]"></div><label><input type="checkbox" v-model="form.is_published"> Show publicly</label><br><button class="btn btn-primary" :disabled="saving">{{ saving ? 'Saving…' : (editing ? 'Update partner' : 'Recognise partner') }}</button><button v-if="editing" type="button" class="btn btn-secondary" @click="reset">Cancel</button></form></div><div class="admin-card"><h2>Recognised partners</h2><table class="table"><thead><tr><th>Name</th><th>Category</th><th>Status</th><th></th></tr></thead><tbody><tr v-for="partner in partners" :key="partner.id"><td>{{ partner.name }}</td><td>{{ partner.category }}</td><td>{{ partner.is_published ? 'Published' : 'Draft' }}</td><td><button class="copy-btn" @click="edit(partner)">Edit</button> <button class="copy-btn danger-btn" @click="remove(partner)">Delete</button></td></tr></tbody></table></div></AdminLayout></template>
<script setup>
import { ref, reactive, onMounted } from 'vue'
import axios from 'axios'
import AdminLayout from '../components/AdminLayout.vue'
const partners = ref([]), editing = ref(null), saving = ref(false), message = ref(''), error = ref('')
const form = reactive({ name: '', category: '', description: '', website_url: '', logo: null, is_published: false })
const load = async () => { try { partners.value = (await axios.get('/api/admin/partners')).data } catch (e) { error.value = e.response?.data?.message || 'Could not load partners.' } }
const reset = () => { editing.value = null; Object.assign(form, { name: '', category: '', description: '', website_url: '', logo: null, is_published: false }) }
const edit = (partner) => { editing.value = partner; Object.assign(form, { ...partner, logo: null }) }
const save = async () => { saving.value = true; error.value = ''; const data = new FormData(); Object.entries(form).forEach(([key, value]) => { if (value !== null && value !== undefined) data.append(key, key === 'is_published' ? (value ? '1' : '0') : value) }); try { if (editing.value) { data.append('_method', 'PUT'); await axios.post(`/api/admin/partners/${editing.value.id}`, data); message.value = 'Partner updated.' } else { await axios.post('/api/admin/partners', data); message.value = 'Partner recognised.' } reset(); await load() } catch (e) { error.value = e.response?.data?.message || 'Could not save partner.' } finally { saving.value = false } }
const remove = async (partner) => { if (!confirm(`Delete ${partner.name}?`)) return; await axios.delete(`/api/admin/partners/${partner.id}`); message.value = 'Partner deleted.'; await load() }
onMounted(load)
</script>
