<template>
<div>
  <RunnerHero />
  
  <section id="about" class="section"><div class="container about-grid"><div><span class="kicker">THE MOVEMENT</span><h2>Culture on the move. Community in motion.</h2><p class="section-lead">Won Nyaci Run is an initiative under the Lango Cultural Institution (Tekwaro A'LANGO), bringing people together through culture, health and practical community action.</p><p class="section-lead">The 2026 run channels the energy of the Lango community toward inclusion — with every kit contributing to a collective fund for free wheelchairs and crutches for people living with disabilities in Lango.</p><RouterLink to="/contact" class="btn btn-primary">Partner with the run →</RouterLink></div><div class="culture-card"><h3>Running for our culture, our health & our future.</h3><p>From the 175 clans of Lango to young people, families, businesses and friends of the region — this is a day to celebrate identity while making a visible difference.</p><div class="pill-row"><span class="pill">Lango Cultural Institution</span><span class="pill">Inclusion</span><span class="pill">Youth & health</span><span class="pill">Community unity</span></div></div></div></section>
  <section id="impact" class="section alt"><div class="container"><div class="section-head"><span class="kicker">WHY WE RUN</span><h2>Your kit becomes a helping hand.</h2><p class="section-lead">The run's proceeds support a collective effort to provide mobility equipment for people with disabilities across Lango.</p></div><div class="impact-grid"><div class="impact-card"><div class="impact-num">30K</div><h3>One kit</h3><p>Standard participant kit price from the official 2026 run information supplied to us.</p></div><div class="impact-card"><div class="impact-num">50K</div><h3>Corporate T-shirt</h3><p>A corporate option for organisations that want to show up together and support the cause.</p></div><div class="impact-card"><div class="impact-num">∞</div><h3>Collective impact</h3><p>Every participant adds momentum to a community-led accessibility and independence effort.</p></div></div></div></section>
  <section class="section"><div class="container"><div class="kit-banner"><div><span class="kicker">24 OCTOBER 2026 · OLD AKII BUA STADIUM</span><h2>Be there when Lango runs together.</h2><p>Registration & aerobics start at 6:00 AM. Running starts at 7:30 AM.</p><RouterLink to="/pay" class="btn btn-secondary">Buy a kit now →</RouterLink></div><div class="kit-price">GET A KIT<strong>30K</strong></div></div></div></section>
  <section class="section alt"><div class="container"><div class="section-head"><span class="kicker">RUN DAY</span><h2>Save the date.</h2></div><div class="schedule"><div class="time-card"><b>6:00</b><span>AM · Registration & aerobics</span><p>Arrive early, collect your kit and warm up with the community.</p></div><div class="time-card"><b>7:30</b><span>AM · Running</span><p>The main run gets underway from Old Akii Bua Stadium.</p></div></div></div></section>
  <section class="section"><div class="container"><div class="section-head"><span class="kicker">LATEST FROM THE JOURNAL</span><h2>Stories from the movement.</h2></div><div v-if="posts.length" class="posts-grid"><article v-for="post in posts" :key="post.id" class="post-card"><img v-if="post.image" class="post-image" :src="asset(post.image)"/><div v-else class="post-image"></div><div class="post-body"><h3>{{post.title}}</h3><p>{{post.excerpt || truncate(post.body)}}</p><RouterLink :to="`/blog/${post.slug}`" class="btn btn-primary">Read story →</RouterLink></div></article></div><div v-else class="culture-card"><h3>Our stories are coming.</h3><p>The CMS is ready for the admin team to publish updates, photos and run stories.</p></div></div></section>
  <section id="x-feed" class="section alt"><div class="container"><div class="section-head"><span class="kicker">LIVE SOCIAL PULSE</span><h2>What we are saying on X.</h2><p class="section-lead">Follow the official run account for announcements, training updates and race-day energy.</p></div><div v-if="xPosts.length" class="x-grid"><article v-for="post in xPosts" :key="post.id" class="x-card"><p>{{post.text}}</p><a :href="post.url" target="_blank" rel="noreferrer">View on X →</a></article></div><div v-else class="culture-card x-empty"><div><h3>Follow @AkaoGloriah</h3><p>The official X profile is ready. Add the X API token in the CMS to mirror the latest posts here automatically.</p></div><a class="btn btn-primary" href="https://x.com/AkaoGloriah" target="_blank" rel="noreferrer">Open X profile →</a></div></div></section>
  <section class="section"><div class="container contact-grid"><div class="contact-panel"><span class="kicker" style="color:#d9ff58">JOIN THE TEAM</span><h2>Let’s make the run bigger than race day.</h2><p>For sponsorships, partnerships, media, volunteers or group registrations, send the team a message.</p><RouterLink to="/contact" class="btn btn-primary">Contact the run →</RouterLink></div><div class="event-poster"><span>24</span><strong>OCT</strong><small>2026 · LIRA</small><i>RUN TOGETHER</i></div></div></section>
</div>
</template>
<script setup>
import { ref, onMounted } from 'vue'
import axios from 'axios'
import RunnerHero from '../components/RunnerHero.vue'
const posts=ref([]), xPosts=ref([])
const asset=(path)=>path?.startsWith('http')?path:(path?.startsWith('images/')?`/${path}`:`/storage/${path}`)
const truncate=(text)=>text?.length>120?text.slice(0,120)+'…':text
onMounted(async()=>{try{const {data}=await axios.get('/api/home');posts.value=data.posts||[];xPosts.value=data.x_posts||[]}catch(e){console.error(e)}})
</script>
